<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ApiOauthUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('user_details')->insert(array (
            0 =>
            array (
                'id' => 12,
                'username' => 'BRYAN',
                'password' => '123456',
                'mob_pho' => '0162163761',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'BRYAN',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => 'bryan@mail.com',
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2020-10-02 13:37:07',
                'updated_at' => '2023-01-04 15:38:35',
            ),
            1 =>
            array (
                'id' => 13,
                'username' => 'tfs163',
                'password' => '123',
                'mob_pho' => '0163364788',
                'idle_tim' => 5,
                'access_pdf' => 'N',
                'first_name' => 'tsen',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2020-10-03 10:32:34',
                'updated_at' => '2020-10-03 10:32:34',
            ),
            2 =>
            array (
                'id' => 14,
                'username' => 'kiew',
                'password' => '123456',
                'mob_pho' => '0126630686',
                'idle_tim' => 5,
                'access_pdf' => 'N',
                'first_name' => 'test',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2021-02-05 06:40:14',
                'updated_at' => '2023-02-02 13:04:24',
            ),
            3 =>
            array (
                'id' => 15,
                'username' => 'datoyew',
                'password' => 'datoyew123',
                'mob_pho' => '0132209966',
                'idle_tim' => 5,
                'access_pdf' => 'N',
                'first_name' => 'DATOYEW',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2021-03-26 10:24:05',
                'updated_at' => '2021-03-26 10:24:05',
            ),
            4 =>
            array (
                'id' => 17,
                'username' => 'SMYERIC',
                'password' => '123',
                'mob_pho' => '0194404011',
                'idle_tim' => 5,
                'access_pdf' => 'N',
                'first_name' => 'SEMENYIH ERIC',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2022-10-12 14:10:19',
                'updated_at' => '2023-04-11 12:46:36',
            ),
            5 =>
            array (
                'id' => 18,
                'username' => 'subunicorn',
                'password' => 'test123456',
                'mob_pho' => '0162118847',
                'idle_tim' => 5,
                'access_pdf' => 'N',
                'first_name' => 'SUBUNICORN DEVELOPER',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2022-12-19 06:26:14',
                'updated_at' => '2023-02-16 08:44:11',
            ),
            6 =>
            array (
                'id' => 19,
                'username' => 'IOSTEST',
                'password' => '12345',
                'mob_pho' => '0163303761',
                'idle_tim' => 6,
                'access_pdf' => 'Y',
                'first_name' => 'IOS TEST',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => 'stanleyloh33@gmail.com',
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-01-20 08:12:18',
                'updated_at' => '2023-01-20 08:12:18',
            ),
            7 =>
            array (
                'id' => 20,
                'username' => 'stanley',
                'password' => 'test123456',
                'mob_pho' => '0126269463',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'Stanley',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => 'stanleyloh33@gmail.com',
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-02-10 06:04:50',
                'updated_at' => '2023-02-10 06:04:50',
            ),
            8 =>
            array (
                'id' => 22,
                'username' => 'BRYANH',
                'password' => 'b123456',
                'mob_pho' => '0123684649',
                'idle_tim' => 5,
                'access_pdf' => 'Y',
                'first_name' => 'BRYAN LAU',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-02-10 09:07:43',
                'updated_at' => '2023-02-10 09:07:43',
            ),
            9 =>
            array (
                'id' => 23,
                'username' => 'chew',
                'password' => 'chew12345',
                'mob_pho' => '0163139832',
                'idle_tim' => 7,
                'access_pdf' => 'Y',
                'first_name' => 'Chew',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-02-18 06:44:30',
                'updated_at' => '2023-02-18 06:44:30',
            ),
            10 =>
            array (
                'id' => 24,
                'username' => 'CHAN',
                'password' => 'test123456',
                'mob_pho' => '0122083761',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'MS CHAN',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-11 08:44:14',
                'updated_at' => '2023-03-11 08:44:14',
            ),
            11 =>
            array (
                'id' => 25,
                'username' => 'Jason',
                'password' => '123456',
                'mob_pho' => '0123396493',
                'idle_tim' => 10,
                'access_pdf' => 'N',
                'first_name' => 'Jason Yong',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-14 08:12:46',
                'updated_at' => '2023-03-14 08:12:46',
            ),
            12 =>
            array (
                'id' => 26,
                'username' => 'iosreview1',
                'password' => 'test123456',
                'mob_pho' => '0162118888',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'IOS tester',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-16 09:54:44',
                'updated_at' => '2023-03-16 09:54:44',
            ),
            13 =>
            array (
                'id' => 27,
                'username' => 'iosreview2',
                'password' => 'test12344423',
                'mob_pho' => '0162118889',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'IOS tester2',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-16 09:56:08',
                'updated_at' => '2023-03-16 09:56:08',
            ),
            14 =>
            array (
                'id' => 28,
                'username' => 'iosreview3',
                'password' => 'test123456',
                'mob_pho' => '0162118890',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'IOS tester3',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-16 09:57:05',
                'updated_at' => '2023-03-28 06:51:41',
            ),
            15 =>
            array (
                'id' => 29,
                'username' => 'iosreview4',
                'password' => 'test123456',
                'mob_pho' => '0162118891',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'IOS tester4',
                'last_name' => '',
                'scope' => 'CHATLIST GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG DELACC',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-03-16 10:07:01',
                'updated_at' => '2023-03-16 10:07:01',
            ),
            16 =>
            array (
                'id' => 30,
                'username' => 'loh',
                'password' => '123456',
                'mob_pho' => '0172801684',
                'idle_tim' => 10,
                'access_pdf' => 'n',
                'first_name' => 'loh',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-04-12 09:17:15',
                'updated_at' => '2023-04-12 09:17:15',
            ),
            17 =>
            array (
                'id' => 31,
                'username' => 'jasontest',
                'password' => '123456',
                'mob_pho' => '0192033111',
                'idle_tim' => 6,
                'access_pdf' => 'Y',
                'first_name' => 'JasonTest',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => NULL,
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-05-02 09:39:56',
                'updated_at' => '2023-05-02 09:39:56',
            ),
            18 =>
            array (
                'id' => 32,
                'username' => 'yeoteckhooi',
                'password' => '123456',
                'mob_pho' => '0178868284',
                'idle_tim' => 10,
                'access_pdf' => 'Y',
                'first_name' => 'YEO TECK HOOI',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => 'NIKKOKL@GMAIL.COM',
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-05-19 13:29:54',
                'updated_at' => '2023-05-19 13:29:54',
            ),
            19 =>
            array (
                'id' => 33,
                'username' => 'EUGENE',
                'password' => '0167024183',
                'mob_pho' => '0167024183',
                'idle_tim' => 10,
                'access_pdf' => 'N',
                'first_name' => 'EUGENE THONG',
                'last_name' => '',
                'scope' => 'CHATLIST DELACC GETBCMSG GETMSG GETNOTIFICATION HISTORYLOG LOGIN MOBUSER ORDERHISTORY ORDERITEM PRODUCTLIST PULLDATA REQDAILY REQMONTHLY SENDAUTHORIZE SENDBCMSG SENDMSG',
                'sm_cod' => '',
                'email' => 'aienb63@gmail.com',
                'prt_1' => '',
                'prt_2' => '',
                'client_id' => 'PWSPGAPP',
                'alw_red' => 'N',
                'created_at' => '2023-05-23 13:42:09',
                'updated_at' => '2023-06-19 12:49:08',
            ),
        ));


    }
}
