<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class ArcnTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        Schema::disableForeignKeyConstraints();
        \DB::table('arcns')->delete();

        \DB::table('arcns')->insert(array (
            0 =>
            array (
                'agents_id' => 2,
                'arcnid' => '6B6BAC6E-991B-48D2-9096-05F79475289D',
                'cncode' => 'CN1607/007',
                'cndate' => '2016-07-13',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 662,
                'customername' => 'FAH NGIEN PAWNSHOP',
                'description' => 'SALES RETURNS',
                'id' => 1,
                'nettotalamount' => '101.75',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '101.75',
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'agents_id' => 1,
                'arcnid' => '772B3A2D-3200-48EB-A259-0B6E39002912',
                'cncode' => 'CN1601/001',
                'cndate' => '2016-01-28',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 298,
                'customername' => 'PAJAK GADAI HOE LEE SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 2,
                'nettotalamount' => '1000.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1000.00',
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'C8EAAB11-F41E-4017-A140-168D0DBFD87C',
                'cncode' => 'CN1607/005',
                'cndate' => '2016-07-12',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 294,
                'customername' => 'CASH',
                'description' => 'SALES RETURNS',
                'id' => 3,
                'nettotalamount' => '159.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '159.00',
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'agents_id' => 1,
                'arcnid' => '15CF8AAE-901E-4F12-892F-1E3917E9ABB6',
                'cncode' => 'CN1612/001',
                'cndate' => '2016-12-26',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 265,
                'customername' => 'PAJAK GADAI LIAN ZHENG SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 4,
                'nettotalamount' => '159.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '150.00',
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'agents_id' => 1,
                'arcnid' => '9183D8C3-70AC-4124-A314-1E58B3CCFF02',
                'cncode' => 'CN1507/004',
                'cndate' => '2015-07-22',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 222,
                'customername' => 'HOONG LEONG PAJAK KEDAI',
                'description' => 'SALES RETURNS',
                'id' => 5,
                'nettotalamount' => '435.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '435.00',
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'C889CA2D-E275-4136-993C-39033ADE16A2',
                'cncode' => 'CN1707/001',
                'cndate' => '2017-07-15',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 172,
                'customername' => 'AUN THYE PAWNSHOP',
                'description' => 'SALES RETURNS',
                'id' => 6,
                'nettotalamount' => '159.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '150.00',
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'C9B02320-023E-48FB-BB2F-45E53C814AB7',
                'cncode' => 'CN1607/001',
                'cndate' => '2016-04-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 410,
                'customername' => 'PAJAK GADAI PAPPAJACK SDN BHD
NO.27, JLN BAYU TINGGI 7,
TMN BAYU TINGGI,
41200 KLANG,
SELANGOR DARUL EHSAN.;',
                'description' => 'SALES RETURNS',
                'id' => 7,
                'nettotalamount' => '900.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '900.00',
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'BB073D9E-6675-4E7F-844A-49BF2B1C7E4F',
                'cncode' => 'CN1509/004',
                'cndate' => '2015-09-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 505,
                'customername' => 'HING FOH PAWNSHOP SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 8,
                'nettotalamount' => '614.80',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '580.00',
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '3932B96B-E17E-4A40-B940-4C3CC27A3D2A',
                'cncode' => 'CN1604/001',
                'cndate' => '2016-04-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 325,
                'customername' => 'PAJAK GADAI KOTA BHARU SDN BHD
PT1556, JLN KK6/1,
BANDAR BARU KUBANG KERIAN,
16150 KOTA BHARU,
KELANTAN.;',
                'description' => 'SALES RETURNS',
                'id' => 9,
                'nettotalamount' => '1590.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1500.00',
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '303F5E6B-AE2B-4BDB-9E4C-5163BE589391',
                'cncode' => 'CN1604/003',
                'cndate' => '2016-04-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 308,
                'customername' => 'PAJAK GADAI SOON LEE
NO.192, JLN AH SANG,
18000 KUALA KRAI,
KELANTAN, MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 10,
                'nettotalamount' => '3000.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '3000.00',
                'updated_at' => NULL,
            ),
            10 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'FA15C52A-5D1C-4C06-8239-57ADF61EBF67',
                'cncode' => 'CN1805/001',
                'cndate' => '2018-05-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 660,
                'customername' => 'PAJAK GADAI ION SDN BHD
NO.28, JLN PINANG 42,
TAMAN DAYA,
81100 JOHOR BAHRU',
                'description' => 'SALES RETURNS',
                'id' => 11,
                'nettotalamount' => '5830.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '5830.00',
                'updated_at' => NULL,
            ),
            11 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '6B279B9B-3342-4A3F-8565-57FF31DD3AD1',
                'cncode' => 'CN1510/001',
                'cndate' => '2015-10-27',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 485,
                'customername' => 'AIK LEE ENTERPRISE',
                'description' => 'SALES RETURNS',
                'id' => 12,
                'nettotalamount' => '29.68',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '28.00',
                'updated_at' => NULL,
            ),
            12 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'D77A0D8D-5609-4E23-A5D6-5B092D9249AC',
                'cncode' => 'CN1805/007',
                'cndate' => '2018-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 325,
                'customername' => 'PAJAK GADAI KOTA BHARU SDN BHD
PT1556, JLN KK6/1,
BANDAR BARU KUBANG KERIAN,
16150 KOTA BHARU,
KELANTAN.',
                'description' => 'SALES RETURNS',
                'id' => 13,
                'nettotalamount' => '1590.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1590.00',
                'updated_at' => NULL,
            ),
            13 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'B1135695-1148-4A84-BD52-5CC35F69DE23',
                'cncode' => 'CN1901/001',
                'cndate' => '2019-01-17',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 466,
                'customername' => 'PAJAK GADAI JIT JIT SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 14,
                'nettotalamount' => '500.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '500.00',
                'updated_at' => NULL,
            ),
            14 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'CB99FC7A-5F25-48C8-B352-5DB72D0D1F6D',
                'cncode' => 'CN1710/002',
                'cndate' => '2017-10-02',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 172,
                'customername' => 'AUN THYE PAWNSHOP
NO.15, JLN TUANKU ABDUL RAHMAN,
50100 KUALA LUMPUR,
MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 15,
                'nettotalamount' => '159.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '150.00',
                'updated_at' => NULL,
            ),
            15 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'FC6995D1-1AEB-4103-8AAD-5EB7E02690FB',
                'cncode' => 'CN1805/005',
                'cndate' => '2018-05-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 323,
                'customername' => 'ION CAPITAL SDN BHD
MO:70, JALAN MOLEK 1/2,
TAMAN MOLEK,
81100 JOHOR BAHRU.',
                'description' => 'SALES RETURNS',
                'id' => 16,
                'nettotalamount' => '5830.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '5830.00',
                'updated_at' => NULL,
            ),
            16 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'DC7183BF-035E-42BE-B1CD-6AD641842CF7',
                'cncode' => 'CN1807/001',
                'cndate' => '2018-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 115,
                'customername' => 'PAJAK GADAI LIAN SHEN SDN BHD
NO.527, PULAU SEBANG,
73000 TAMPIN,
NEGERI MELAKA,
MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 17,
                'nettotalamount' => '530.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '530.00',
                'updated_at' => NULL,
            ),
            17 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '20272EE3-01D3-488D-B6BE-6B4EC804B4B3',
                'cncode' => 'CN1707/003',
                'cndate' => '2017-07-17',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 182,
                'customername' => 'PAJAK GADAI MENTAKAB SDN BHD
NO.25, JLN ZAIBIDIN,
28400 MENTAKAB,
PAHANG DARUL MAKMUR,
MALAYSIA.;',
                'description' => 'BW-A01732',
                'id' => 18,
                'nettotalamount' => '45.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '45.00',
                'updated_at' => NULL,
            ),
            18 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'E9C7988C-03F2-4711-B97D-74C56D97EA18',
                'cncode' => 'CN1512/001',
                'cndate' => '2015-12-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 558,
                'customername' => 'PAJAK GADAI PUCHONG PERMAI SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 19,
                'nettotalamount' => '1166.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1100.00',
                'updated_at' => NULL,
            ),
            19 =>
            array (
                'agents_id' => 1,
                'arcnid' => '2DEFF4F7-1423-42E2-AC9E-7D62C27D0243',
                'cncode' => 'CN1808/001',
                'cndate' => '2018-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 95,
                'customername' => 'KEDAI PAJAK SHIN NGIEN SDN BHD
NO.631, JLN SATU, SERI SETIA,
47300 SUNGEI WAY,
SELANGOR DARUL EHSAN.
MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 20,
                'nettotalamount' => '1180.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1180.00',
                'updated_at' => NULL,
            ),
            20 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '7446A0AA-C697-4BAC-819B-8646C46597F0',
                'cncode' => 'CN1607/004',
                'cndate' => '2016-07-11',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 359,
                'customername' => 'JIT JIT PAJAK GADAI',
                'description' => 'SALES RETURNS',
                'id' => 21,
                'nettotalamount' => '76.30',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '76.30',
                'updated_at' => NULL,
            ),
            21 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '5D9BA45D-5B00-4043-8FB2-88C3B30025A3',
                'cncode' => 'CN1509/003',
                'cndate' => '2015-09-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 93,
                'customername' => 'PAJAK GADAI NEWKAYA SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 22,
                'nettotalamount' => '795.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '750.00',
                'updated_at' => NULL,
            ),
            22 =>
            array (
                'agents_id' => 1,
                'arcnid' => '4BA74F01-2B63-4A6B-82AE-8B770DC2856D',
                'cncode' => 'CN1707/002',
                'cndate' => '2017-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 388,
                'customername' => 'PAJAK GADAI SIN YUNG SDN BHD
NO:17, JLN SS 2/1,
BANDAR CHERAS BATU 11,
JLN CHERAS, 43200 KAJANG,
SELANGOR DARUL EHSAN.;',
                'description' => 'SALES RETURNS',
                'id' => 23,
                'nettotalamount' => '222.60',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '210.00',
                'updated_at' => NULL,
            ),
            23 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'F6514A3D-B3BA-4D32-A9D3-93EE1EE5347B',
                'cncode' => 'CN1805/003',
                'cndate' => '2018-05-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 216,
                'customername' => 'PAJAK GADAI RAWANG SDN BHD
NO.13, JALAN WELMAN,
48000 RAWANG,
SELANGOR DARUL EHSAN.',
                'description' => 'SALES RETURNS',
                'id' => 24,
                'nettotalamount' => '1007.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1007.00',
                'updated_at' => NULL,
            ),
            24 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'A6FA73F6-1778-4641-91E8-978D42F61DEC',
                'cncode' => 'CN1706/002',
                'cndate' => '2017-06-21',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 388,
                'customername' => 'PAJAK GADAI SIN YUNG SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 25,
                'nettotalamount' => '222.60',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '210.00',
                'updated_at' => NULL,
            ),
            25 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'FF6EB2E4-F108-4487-A8DA-A138AC58D6EA',
                'cncode' => 'CN1805/002',
                'cndate' => '2018-05-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 115,
                'customername' => 'PAJAK GADAI LIAN SHEN SDN BHD
NO.527, PULAU SEBANG,
73000 TAMPIN,
NEGERI MELAKA,
MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 26,
                'nettotalamount' => '530.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '530.00',
                'updated_at' => NULL,
            ),
            26 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'DD7A2ED2-6BBC-4AF3-84B9-A910BF89C5AB',
                'cncode' => 'CN1604/002',
                'cndate' => '2016-04-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 351,
                'customername' => 'PAJAK GADAI BERTUAH SDN BHD
A-01-01, PANGSAPURI AMAN,
JLN PRIMA 6/1,
TMN PUCHONG PRIMA,
47100 PUCHONG, SELANGOR DARUL EHSAN.;',
                'description' => 'SALES RETURNS',
                'id' => 27,
                'nettotalamount' => '900.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '900.00',
                'updated_at' => NULL,
            ),
            27 =>
            array (
                'agents_id' => 1,
                'arcnid' => '0E909B71-63B8-4C7A-B4EB-AA657B9E0A4B',
                'cncode' => 'CN1607/003',
                'cndate' => '2016-07-08',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 217,
                'customername' => 'PAJAK GADAI FAH ONN',
                'description' => 'SALES RETURNS',
                'id' => 28,
                'nettotalamount' => '196.10',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '196.10',
                'updated_at' => NULL,
            ),
            28 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '43C397FC-7322-48C7-B3BB-AD9B59D417B2',
                'cncode' => 'CN1507/002',
                'cndate' => '2015-07-20',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 287,
                'customername' => 'FAH ONN GOLDSMITH SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 29,
                'nettotalamount' => '530.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '500.00',
                'updated_at' => NULL,
            ),
            29 =>
            array (
                'agents_id' => NULL,
                'arcnid' => 'DF6B8047-8DCD-423F-A6E4-B020BF6B3818',
                'cncode' => 'CN1607/006',
                'cndate' => '2016-07-13',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 294,
                'customername' => 'CASH',
                'description' => 'SALES RETURNS',
                'id' => 30,
                'nettotalamount' => '95.40',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '95.40',
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '97FA6774-EB1B-4F7E-AD04-C83CEB883A33',
                'cncode' => 'CN1509/001',
                'cndate' => '2015-09-08',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 141,
                'customername' => 'PAJAK GADAI EMAS 88 SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 32,
                'nettotalamount' => '530.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '500.00',
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '2386FEDE-D161-494C-90BA-C8A9DF99EA97',
                'cncode' => 'CN1507/003',
                'cndate' => '2015-07-22',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 174,
                'customername' => 'PAJAK GADAI SEGAMAT SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 33,
                'nettotalamount' => '120.85',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '120.85',
                'updated_at' => NULL,
            ),
            32 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '1405504C-C9CA-4B4D-90C3-CD1A0B8AAE6B',
                'cncode' => 'CN1607/002',
                'cndate' => '2016-07-05',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 576,
                'customername' => 'PAJAK GADAI WW & WY SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 34,
                'nettotalamount' => '1590.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1590.00',
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '24444F0B-931C-47F0-AAFF-CD3F16A72C5B',
                'cncode' => 'CN1805/004',
                'cndate' => '2018-05-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 294,
                'customername' => 'CASH',
                'description' => 'SALES RETURNS',
                'id' => 35,
                'nettotalamount' => '95.40',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '95.40',
                'updated_at' => NULL,
            ),
            34 =>
            array (
                'agents_id' => 1,
                'arcnid' => '7B86FA5B-6E2A-4C8D-BC2C-CE1DF430E1F2',
                'cncode' => 'CN1508/001',
                'cndate' => '2015-08-08',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 129,
                'customername' => 'PAJAK GADAI KOK BIN SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 36,
                'nettotalamount' => '466.70',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '440.28',
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'D4430B67-26D9-4919-B7AC-D56A82E0911E',
                'cncode' => 'CN1909/001',
                'cndate' => '2019-09-19',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 88,
                'customername' => 'KIAN LEE JEWELLERS & GOLDSMITH SDN BHD',
                'description' => 'DISCOUNT FOR INV NO. BW-A03964 DD:26/03/2019',
                'id' => 37,
                'nettotalamount' => '470.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '470.00',
                'updated_at' => '2021-01-21 08:20:34',
            ),
            36 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '1A06E4B8-1AC2-4AD0-8872-DE14ABD47F20',
                'cncode' => 'CN1507/005',
                'cndate' => '2015-07-22',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 397,
                'customername' => 'MING CHUAN JEWELS SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 38,
                'nettotalamount' => '2120.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '2000.00',
                'updated_at' => NULL,
            ),
            37 =>
            array (
                'agents_id' => 1,
                'arcnid' => '6059BDE6-3F00-4F2D-B4BA-E57EE5B18EAE',
                'cncode' => 'CN1805/006',
                'cndate' => '2018-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 265,
                'customername' => 'PAJAK GADAI LIAN ZHENG SDN BHD
NO:10, JLN TAMBATAN,
81900 KOTA TINGGI,
JOHOR.',
                'description' => 'SALES RETURNS',
                'id' => 39,
                'nettotalamount' => '168.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '168.00',
                'updated_at' => NULL,
            ),
            38 =>
            array (
                'agents_id' => 1,
                'arcnid' => '8019EFBB-1EAB-4FCF-B613-EA0974AD4569',
                'cncode' => 'CN1706/001',
                'cndate' => '2017-06-21',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 525,
                'customername' => 'PAJAK GADAI KWON TUNG KEE SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 40,
                'nettotalamount' => '1150.10',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '1085.00',
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'agents_id' => 1,
                'arcnid' => '5C05A6F9-6885-46B1-B700-EA54CE94FFAE',
                'cncode' => 'CN1710/001',
                'cndate' => '2017-10-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 294,
                'customername' => 'CASH',
                'description' => 'SALES RETURNS',
                'id' => 41,
                'nettotalamount' => '95.40',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '90.00',
                'updated_at' => NULL,
            ),
            40 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '5B7D88D9-46F4-4823-9584-EBDE19932396',
                'cncode' => 'CN1508/002',
                'cndate' => '2015-08-18',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 434,
                'customername' => 'KEDAI EMAS SUNSHINES',
                'description' => 'SALES RETURNS',
                'id' => 42,
                'nettotalamount' => '320.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '320.00',
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'FBBDC15E-6182-47A2-9285-EF11A8EC6B20',
                'cncode' => 'CN1805/008',
                'cndate' => '2018-07-01',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 217,
                'customername' => 'PAJAK GADAI FAH ONN
NO.17, JLN BESAR,
43000 KAJANG,
SELANGOR DARUL EHSAN,
MALAYSIA.',
                'description' => 'SALES RETURNS',
                'id' => 43,
                'nettotalamount' => '196.10',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '196.10',
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'agents_id' => 1,
                'arcnid' => 'AF0BD699-1F8F-4294-A052-EFFA3295347A',
                'cncode' => 'CN1509/002',
                'cndate' => '2015-09-30',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 525,
                'customername' => 'PAJAK GADAI KWON TUNG KEE SDN BHD',
                'description' => 'SALES RETURNS',
                'id' => 44,
                'nettotalamount' => '80.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '80.00',
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'agents_id' => 1,
                'arcnid' => '6CC89053-BDCB-474A-9F96-FD149A8535B7',
                'cncode' => 'CN1911/001',
                'cndate' => '2019-11-29',
                'companyid' => 1,
                'created_at' => NULL,
                'currencies_id' => 1,
                'customers_id' => 633,
                'customername' => 'LOVE ME JEWELRY SDN BHD
LGK-02, THE MALL,
MID VALLEY SOUTHKEY,
PERSIARAN SOUTHKEY 1,
80150 JOHOR BAHRU, JOHOR.',
                'description' => 'SALES RETURNS',
                'id' => 45,
                'nettotalamount' => '284.00',
                'reason' => NULL,
                'referenceno' => '',
                'totalamount' => '284.00',
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/003',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:11:31',
                'currencies_id' => 1,
                'customers_id' => 546,
                'customername' => 'KEDAI PAJAK GADAI DENGKIL SDN BHD',
                'description' => 'INV NO.A03091 DD:19/04/2018 - CUSTOMER REQUEST CANCEL',
                'id' => 52,
                'nettotalamount' => '174.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '174.00',
                'updated_at' => '2020-01-30 14:11:31',
            ),
            45 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/002',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:05:02',
                'currencies_id' => 1,
                'customers_id' => 557,
                'customername' => 'PAJAK GADAI JETRIH JAYA',
                'description' => 'INV NO.A04360 DD:12/09/2019 DISCOUNT ALLOW',
                'id' => 51,
                'nettotalamount' => '500.00',
                'reason' => 'DISCOUNT ALLOW',
                'referenceno' => NULL,
                'totalamount' => '500.00',
                'updated_at' => '2021-04-05 10:05:06',
            ),
            46 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1911/002',
                'cndate' => '2019-11-29',
                'companyid' => 1,
                'created_at' => '2020-01-10 14:18:19',
                'currencies_id' => 1,
                'customers_id' => 633,
                'customername' => 'LOVE ME JEWELRY SDN BHD',
                'description' => 'DISCOUNT FOR INV NO. A04516, A04570',
                'id' => 50,
                'nettotalamount' => '284.00',
                'reason' => 'DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '284.00',
                'updated_at' => '2020-01-10 14:18:19',
            ),
            47 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/001',
                'cndate' => '2019-12-28',
                'companyid' => 1,
                'created_at' => '2019-12-28 07:31:48',
                'currencies_id' => 1,
                'customers_id' => 273,
                'customername' => 'PAJAK GADAI KOK FONG CEMERLANG SDN BHD',
                'description' => 'DISCOUNT FOR INV NO.A04310 DD:19/08/2019',
                'id' => 49,
                'nettotalamount' => '206.00',
                'reason' => 'DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '206.00',
                'updated_at' => '2019-12-28 07:39:17',
            ),
            48 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/004',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:13:04',
                'currencies_id' => 1,
                'customers_id' => 173,
                'customername' => 'PAJAK GADAI SIN FOONG TONG SDN BHD',
                'description' => 'INV NO.A03779 DD:02/02/2019 - REQUEST DISCOUNT',
                'id' => 53,
                'nettotalamount' => '2.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '2.00',
                'updated_at' => '2020-01-30 14:13:04',
            ),
            49 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/005',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:17:26',
                'currencies_id' => 1,
                'customers_id' => 182,
                'customername' => 'PAJAK GADAI MENTAKAB SDN BHD',
                'description' => 'INV NO.A01732 DD:16/02/2017 - REQUEST DISCOUNT',
                'id' => 54,
                'nettotalamount' => '45.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '45.00',
                'updated_at' => '2020-01-30 14:18:09',
            ),
            50 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/006',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:19:04',
                'currencies_id' => 1,
                'customers_id' => 86,
                'customername' => 'PAJAK GADAI HONG SENG SDN BHD',
                'description' => 'INV NO.A04004 DD:10/04/2019 - CANCEL ITEM',
                'id' => 55,
                'nettotalamount' => '230.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '230.00',
                'updated_at' => '2020-01-30 14:19:04',
            ),
            51 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/007',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:20:01',
                'currencies_id' => 1,
                'customers_id' => 407,
                'customername' => 'PAJAK GADAI NAM LOONG',
                'description' => 'INV NO.A02347 DD:09/11/2017 - CANCEL ITEM',
                'id' => 56,
                'nettotalamount' => '57.24',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '57.24',
                'updated_at' => '2020-01-30 14:20:01',
            ),
            52 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/008',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:21:19',
                'currencies_id' => 1,
                'customers_id' => 359,
                'customername' => 'JIT JIT PAJAK GADAI',
                'description' => 'INV NO.A00638 DD:06/01/2016 - CANCEL ITEM',
                'id' => 57,
                'nettotalamount' => '76.32',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '76.32',
                'updated_at' => '2020-01-30 14:21:19',
            ),
            53 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/009',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:22:41',
                'currencies_id' => 1,
                'customers_id' => 466,
                'customername' => 'PAJAK GADAI JIT JIT SDN BHD',
                'description' => 'INV NO.A03620 DD:07/01/2019 - REQUEST DISCOUNT',
                'id' => 58,
                'nettotalamount' => '500.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '500.00',
                'updated_at' => '2020-01-30 14:22:41',
            ),
            54 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/010',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:23:42',
                'currencies_id' => 1,
                'customers_id' => 557,
                'customername' => 'PAJAK GADAI JETRIH JAYA',
                'description' => 'INV NO.A02946 DD:01/06/2018 - REQUEST DISCOUNT',
                'id' => 59,
                'nettotalamount' => '2000.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '2000.00',
                'updated_at' => '2020-01-30 14:23:42',
            ),
            55 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/011',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:27:16',
                'currencies_id' => 1,
                'customers_id' => 432,
                'customername' => 'PAJAK GADAI REAL GOLD',
                'description' => 'INV NO.A03591 DD:02/01/2019 - REQUEST DISCOUNT',
                'id' => 60,
                'nettotalamount' => '1125.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '1125.00',
                'updated_at' => '2020-01-30 14:27:16',
            ),
            56 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/012',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:28:15',
                'currencies_id' => 1,
                'customers_id' => 102,
                'customername' => 'PAJAK GADAI SARIKEI GOLDSMITH SDN BHD',
                'description' => 'INV NO.A02109 DD:01/08/2017 - REQUEST DISCOUNT',
                'id' => 61,
                'nettotalamount' => '17.12',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '17.12',
                'updated_at' => '2020-01-30 14:28:15',
            ),
            57 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/013',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-01-30 14:29:07',
                'currencies_id' => 1,
                'customers_id' => 391,
                'customername' => 'PAJAK GADAI WANG GOLDSMITH',
                'description' => 'INV NO.A03550 DD:13/12/2018 - CLOSE SHOP',
                'id' => 62,
                'nettotalamount' => '750.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '750.00',
                'updated_at' => '2020-01-30 14:29:07',
            ),
            58 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2002/001',
                'cndate' => '2020-02-03',
                'companyid' => 1,
                'created_at' => '2020-01-31 12:09:25',
                'currencies_id' => 1,
                'customers_id' => 543,
                'customername' => 'PAJAK GADAI WAN SIN',
                'description' => 'INV NO.A04679 DD:24/12/2019 - CUSTOMER REQUEST DISCOUNT',
                'id' => 63,
                'nettotalamount' => '100.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '100.00',
                'updated_at' => '2020-01-31 12:09:25',
            ),
            59 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1912/014',
                'cndate' => '2019-12-30',
                'companyid' => 1,
                'created_at' => '2020-02-17 10:04:17',
                'currencies_id' => 1,
                'customers_id' => 63,
                'customername' => 'PAJAK GADAI CHEN CHANG HIN SDN BHD',
                'description' => 'INV NO.A03482 DD:30/11/2018 - CANCEL ORDER',
                'id' => 64,
                'nettotalamount' => '290.00',
                'reason' => 'CANCEL ORDER',
                'referenceno' => NULL,
                'totalamount' => '290.00',
                'updated_at' => '2020-02-17 10:07:08',
            ),
            60 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2002/002',
                'cndate' => '2020-02-24',
                'companyid' => 1,
                'created_at' => '2020-02-24 08:25:08',
                'currencies_id' => 1,
                'customers_id' => 77,
                'customername' => 'EVER BUSINESS CAPITAL PAWNSHOP SDN BHD - KK',
                'description' => 'INV NO.A04537 DD:26/11/2019 - CUSTOMER REQUEST DISCOUNT.',
                'id' => 65,
                'nettotalamount' => '1200.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '1200.00',
                'updated_at' => '2020-02-24 08:25:08',
            ),
            61 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2002/003',
                'cndate' => '2020-02-24',
                'companyid' => 1,
                'created_at' => '2020-02-24 08:27:35',
                'currencies_id' => 1,
                'customers_id' => 340,
                'customername' => 'PAJAK GADAI THYE FOH SDN BHD',
                'description' => 'INV NO.A04713 DD:02/01/2020 -CANCELLED INVOICE.',
                'id' => 66,
                'nettotalamount' => '184.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '184.00',
                'updated_at' => '2020-02-24 08:27:35',
            ),
            62 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '',
                'cncode' => 'CN2002/004',
                'cndate' => '2020-02-25',
                'companyid' => 1,
                'created_at' => '2020-02-25 12:58:52',
                'currencies_id' => 1,
                'customers_id' => 681,
                'customername' => 'SKY GOLD TRADING',
                'description' => 'INV NO.A04863 DD:03/02/2020 - CANCELLATION OF MYCAD IC CARD READER C/W TOUCH.',
                'id' => 67,
                'nettotalamount' => '550.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '550.00',
                'updated_at' => '2020-02-25 13:00:25',
            ),
            63 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2003/001',
                'cndate' => '2020-03-05',
                'companyid' => 1,
                'created_at' => '2020-03-05 07:21:41',
                'currencies_id' => 1,
                'customers_id' => 458,
                'customername' => 'KEDAI EMAS RAJAMAS - INANAM',
                'description' => 'INV NO.A04546 DD:26/11/2019 - CANCL INVOICE',
                'id' => 68,
                'nettotalamount' => '700.00',
                'reason' => 'CUSTOMER REQUEST CANCEL.',
                'referenceno' => NULL,
                'totalamount' => '700.00',
                'updated_at' => '2020-03-05 07:21:41',
            ),
            64 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '',
                'cncode' => 'CN2003/002',
                'cndate' => '2020-03-12',
                'companyid' => 1,
                'created_at' => '2020-03-12 10:02:41',
                'currencies_id' => 1,
                'customers_id' => 350,
                'customername' => 'COMPACT STATION ENTERPRISE',
                'description' => 'INV NO.A04852 DD:03/02/2020 - CUSTOMER REQUEST DISCOUNT.',
                'id' => 69,
                'nettotalamount' => '2000.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '2000.00',
                'updated_at' => '2020-03-12 10:12:29',
            ),
            65 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2006/001',
                'cndate' => '2020-06-20',
                'companyid' => 1,
                'created_at' => '2020-06-20 08:57:07',
                'currencies_id' => 1,
                'customers_id' => 229,
            'customername' => 'PAJAK GADAI KIAN SHIN (NILAI LAMA)',
                'description' => 'INV NO.A05122 DD:17/06/20 - CANCEL 4 PORT HUB',
                'id' => 70,
                'nettotalamount' => '120.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '120.00',
                'updated_at' => '2020-06-20 08:58:22',
            ),
            66 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2006/002',
                'cndate' => '2020-06-20',
                'companyid' => 1,
                'created_at' => '2020-06-20 09:00:10',
                'currencies_id' => 1,
                'customers_id' => 662,
                'customername' => 'FAH NGIEN PAWNSHOP',
                'description' => 'INV NO.A04994 DD:10/03/20 - CANCEL 4 PORT HUB',
                'id' => 71,
                'nettotalamount' => '120.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '120.00',
                'updated_at' => '2020-06-20 09:00:10',
            ),
            67 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2009/001',
                'cndate' => '2020-09-06',
                'companyid' => 1,
                'created_at' => '2020-09-06 05:32:10',
                'currencies_id' => 1,
                'customers_id' => 700,
                'customername' => 'PAJAK GADAI PPJ SINAR SDN BHD',
                'description' => 'INV NO.A05041 DD:19/05/2020 - CANCELLATION TO SEPT 20 INVOICE',
                'id' => 72,
                'nettotalamount' => '5534.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '5534.00',
                'updated_at' => '2020-09-06 05:32:42',
            ),
            68 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2010/001',
                'cndate' => '2020-10-08',
                'companyid' => 1,
                'created_at' => '2020-10-08 14:04:44',
                'currencies_id' => 1,
                'customers_id' => 150,
                'customername' => 'PAJAK GADAI VAN HIN SDN BHD',
                'description' => 'INV NO.A05366 DD:07/10/20 - REQUEST DISCOUNT',
                'id' => 73,
                'nettotalamount' => '500.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '500.00',
                'updated_at' => '2020-10-08 14:04:44',
            ),
            69 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2011/001',
                'cndate' => '2020-11-28',
                'companyid' => 1,
                'created_at' => '2020-11-28 12:32:21',
                'currencies_id' => 1,
                'customers_id' => 724,
                'customername' => 'PAJAK GADAI PANDAMARAN CEMERLANG SDN BHD',
                'description' => 'DISCOUNT FOR INV NO.A05311 DD:17/09/2020',
                'id' => 74,
                'nettotalamount' => '115.00',
                'reason' => 'CUSTOMER REQUEST FOR DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '115.00',
                'updated_at' => '2020-11-28 12:32:51',
            ),
            70 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '',
                'cncode' => 'CN2012/001',
                'cndate' => '2020-12-05',
                'companyid' => 1,
                'created_at' => '2020-12-05 06:46:05',
                'currencies_id' => 1,
                'customers_id' => 115,
                'customername' => 'PAJAK GADAI LIAN SHEN SDN BHD',
                'description' => 'CANCELLATION FOR THIE INVOICE',
                'id' => 75,
                'nettotalamount' => '1020.00',
                'reason' => '16 CHN DVR PROBLEM',
                'referenceno' => NULL,
                'totalamount' => '1020.00',
                'updated_at' => '2020-12-05 06:46:05',
            ),
            71 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2103/001',
                'cndate' => '2021-03-16',
                'companyid' => 1,
                'created_at' => '2021-03-16 09:54:53',
                'currencies_id' => 1,
                'customers_id' => 146,
                'customername' => 'KEDAI EMAS 101',
                'description' => 'INV NO.A05593 DD:16/12/2020',
                'id' => 78,
                'nettotalamount' => '500.00',
                'reason' => 'CUSTOMER REQUEST DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '500.00',
                'updated_at' => '2021-03-16 09:55:26',
            ),
            72 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2101/001',
                'cndate' => '2021-01-02',
                'companyid' => 1,
                'created_at' => '2021-01-02 12:55:36',
                'currencies_id' => 1,
                'customers_id' => 458,
                'customername' => 'KEDAI EMAS RAJAMAS - INANAM',
                'description' => 'INV NO.A05596 DD:16/12/2020 - CANCELLATION INVOICE',
                'id' => 77,
                'nettotalamount' => '700.00',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '700.00',
                'updated_at' => '2021-01-02 12:56:38',
            ),
            73 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN1910/001',
                'cndate' => '2019-10-31',
                'companyid' => 1,
                'created_at' => '2021-04-02 10:44:40',
                'currencies_id' => 1,
                'customers_id' => 557,
                'customername' => 'PAJAK GADAI JETRIH JAYA',
                'description' => 'DISCOUNT ALLOW',
                'id' => 79,
                'nettotalamount' => '250.00',
                'reason' => 'CUSTOMER REQUEST DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '250.00',
                'updated_at' => '2021-04-02 10:44:40',
            ),
            74 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2105/001',
                'cndate' => '2021-05-19',
                'companyid' => 1,
                'created_at' => '2021-05-19 12:02:45',
                'currencies_id' => 1,
                'customers_id' => 725,
                'customername' => 'PAJAK GADAI UPAYA MAJU SDN BHD',
                'description' => 'INV NO.A05454 DD:20/11/2020',
                'id' => 80,
                'nettotalamount' => '1900.00',
                'reason' => '* CUSTOMER RETURN OKI PRINTER.',
                'referenceno' => NULL,
                'totalamount' => '1900.00',
                'updated_at' => '2021-05-19 12:55:04',
            ),
            75 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2107/001',
                'cndate' => '2021-07-05',
                'companyid' => 1,
                'created_at' => '2021-07-05 06:40:44',
                'currencies_id' => 1,
                'customers_id' => 766,
                'customername' => 'WEI WEI VENTURES SDN BHD',
                'description' => 'INV NO.A06081 DD:26/06/2021',
                'id' => 81,
                'nettotalamount' => '210.00',
                'reason' => '* CUSTOMER RETURN TP-LINK PRINT SERVER.',
                'referenceno' => NULL,
                'totalamount' => '210.00',
                'updated_at' => '2021-07-05 06:40:44',
            ),
            76 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2107/002',
                'cndate' => '2021-07-28',
                'companyid' => 1,
                'created_at' => '2021-07-28 10:18:08',
                'currencies_id' => 1,
                'customers_id' => 657,
                'customername' => 'PAJAK GADAI HENG LEE SDN BHD',
                'description' => 'INV NO.A06106 DD:26/07/2021 - ITEM NO 1',
                'id' => 82,
                'nettotalamount' => '300.00',
                'reason' => 'CUSTOMER REQUEST DISCOUNT',
                'referenceno' => NULL,
                'totalamount' => '300.00',
                'updated_at' => '2021-07-28 10:18:08',
            ),
            77 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2212/001',
                'cndate' => '2022-12-31',
                'companyid' => 1,
                'created_at' => '2022-12-31 12:28:41',
                'currencies_id' => 1,
                'customers_id' => 741,
                'customername' => 'KEDAI PAJAK GADAI SEHATI SDN BHD',
                'description' => 'DISCOUNT FOR INVOICE NO. BW-A07569',
                'id' => 83,
                'nettotalamount' => '106.85',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '106.85',
                'updated_at' => '2022-12-31 12:28:41',
            ),
            78 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2212/002',
                'cndate' => '2022-12-31',
                'companyid' => 1,
                'created_at' => '2022-12-31 12:30:11',
                'currencies_id' => 1,
                'customers_id' => 755,
            'customername' => 'KEDAI PAJAK GADAI SEHATI (PUCHONG) SDN BHD',
                'description' => 'DISCOUNT FOR INVOICE NO. BW-A07568',
                'id' => 84,
                'nettotalamount' => '431.50',
                'reason' => NULL,
                'referenceno' => NULL,
                'totalamount' => '431.50',
                'updated_at' => '2022-12-31 12:30:11',
            ),
            79 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2212/003',
                'cndate' => '2022-12-31',
                'companyid' => 1,
                'created_at' => '2023-01-14 08:21:01',
                'currencies_id' => 1,
                'customers_id' => 729,
                'customername' => 'PAJAK GADAI TA NINETY SDN BHD',
            'description' => 'INVOICE START AT 23/2/22- 31/12/22 (DISOUNT 53DAYS)',
                'id' => 85,
                'nettotalamount' => '217.80',
                'reason' => '1500/365X53DAYS=217.80',
                'referenceno' => NULL,
                'totalamount' => '217.80',
                'updated_at' => '2023-01-14 08:21:01',
            ),
            80 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '',
                'cncode' => 'CN2212/004',
                'cndate' => '2022-12-31',
                'companyid' => 1,
                'created_at' => '2023-01-14 08:22:36',
                'currencies_id' => 1,
                'customers_id' => 750,
                'customername' => 'PAJAK GADAI JRP EMAS SDN BHD',
            'description' => 'INVOICE START 19/3/22 - 31/12/22 (DISCOUNT 77DAYS)',
                'id' => 86,
                'nettotalamount' => '316.45',
                'reason' => '1500/365X77DAYS=316.45',
                'referenceno' => NULL,
                'totalamount' => '316.45',
                'updated_at' => '2023-01-14 08:22:36',
            ),
            81 =>
            array (
                'agents_id' => NULL,
                'arcnid' => '',
                'cncode' => 'CN2212/005',
                'cndate' => '2022-12-31',
                'companyid' => 1,
                'created_at' => '2023-01-14 08:23:52',
                'currencies_id' => 1,
                'customers_id' => 749,
                'customername' => 'PAJAK GADAI AN MAJU SDN BHD',
            'description' => 'INVOICE START 19/3/22-31/12/22(DISCOUNT 77DAYS)',
                'id' => 87,
                'nettotalamount' => '316.45',
                'reason' => '1500/365X77DAYS=316.45',
                'referenceno' => NULL,
                'totalamount' => '316.45',
                'updated_at' => '2023-01-14 08:23:52',
            ),
            82 =>
            array (
                'agents_id' => 1,
                'arcnid' => '',
                'cncode' => 'CN2303/001',
                'cndate' => '2023-03-25',
                'companyid' => 1,
                'created_at' => '2023-03-25 06:44:25',
                'currencies_id' => 1,
                'customers_id' => 337,
                'customername' => 'KEDAI EMAS ION SDN BHD',
                'description' => NULL,
                'id' => 89,
                'nettotalamount' => '4000.00',
                'reason' => 'REFER TO INV NO.A07690 DD:28/02/2023 - DISCOUNT TO CUSTOMER',
                'referenceno' => NULL,
                'totalamount' => '4000.00',
                'updated_at' => '2023-03-25 06:53:04',
            ),
        ));

        Schema::enableForeignKeyConstraints();
    }
}
