<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;


class CustomerPwspgappTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
		Schema::disableForeignKeyConstraints();
        \DB::table('customer_pwspgapps')->delete();
        
        \DB::table('customer_pwspgapps')->insert(array (
            0 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.14/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-14 08:12:46',
                'customers_id' => 838,
                'id' => 159,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-14 08:12:46',
                'users_id' => 25,
                'username' => 'USER',
            ),
            1 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-18 06:44:31',
                'customers_id' => 769,
                'id' => 152,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-18 06:44:31',
                'users_id' => 23,
                'username' => 'USER',
            ),
            2 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.16/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-14 08:12:46',
                'customers_id' => 837,
                'id' => 158,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-14 08:12:46',
                'users_id' => 25,
                'username' => 'USER',
            ),
            3 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2022-10-12 13:21:26',
                'customers_id' => 770,
                'id' => 128,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2022-10-12 13:21:26',
                'users_id' => 13,
                'username' => 'USER',
            ),
            4 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2022-10-12 13:21:21',
                'customers_id' => 769,
                'id' => 127,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2022-10-12 13:21:21',
                'users_id' => 13,
                'username' => 'USER',
            ),
            5 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-14 08:09:18',
                'customers_id' => 770,
                'id' => 149,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-14 08:09:18',
                'users_id' => 19,
                'username' => 'USER',
            ),
            6 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-11 08:44:14',
                'customers_id' => 770,
                'id' => 157,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-11 08:44:14',
                'users_id' => 24,
                'username' => 'USER',
            ),
            7 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-11 08:44:14',
                'customers_id' => 769,
                'id' => 156,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-11 08:44:14',
                'users_id' => 24,
                'username' => 'USER',
            ),
            8 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-18 10:12:33',
                'customers_id' => 770,
                'id' => 155,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-18 10:12:33',
                'users_id' => 14,
                'username' => 'USER',
            ),
            9 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-01-04 15:38:36',
                'customers_id' => 770,
                'id' => 133,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-01-04 15:38:36',
                'users_id' => 12,
                'username' => 'USER',
            ),
            10 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-16 08:44:13',
                'customers_id' => 770,
                'id' => 151,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-16 08:44:13',
                'users_id' => 18,
                'username' => 'USER',
            ),
            11 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-14 06:26:50',
                'customers_id' => 769,
                'id' => 145,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-14 06:26:50',
                'users_id' => 19,
                'username' => 'USER',
            ),
            12 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.33.12/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2021-03-26 10:24:05',
                'customers_id' => 619,
                'id' => 86,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2021-03-26 10:24:05',
                'users_id' => 15,
                'username' => 'USER',
            ),
            13 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-10 09:07:43',
                'customers_id' => 770,
                'id' => 144,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-10 09:07:43',
                'users_id' => 22,
                'username' => 'USER',
            ),
            14 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-10 09:07:43',
                'customers_id' => 769,
                'id' => 143,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-10 09:07:43',
                'users_id' => 22,
                'username' => 'USER',
            ),
            15 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.44.11/lspws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-05-23 13:42:09',
                'customers_id' => 551,
                'id' => 175,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-05-23 13:42:09',
                'users_id' => 33,
                'username' => 'USER',
            ),
            16 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.16/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-05-19 13:29:54',
                'customers_id' => 837,
                'id' => 174,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-05-19 13:29:54',
                'users_id' => 32,
                'username' => 'USER',
            ),
            17 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.33.15/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2021-03-27 10:07:51',
                'customers_id' => 739,
                'id' => 91,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2021-03-27 10:07:51',
                'users_id' => 15,
                'username' => 'USER',
            ),
            18 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.33.14/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2021-03-29 07:12:42',
                'customers_id' => 742,
                'id' => 92,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2021-03-29 07:12:42',
                'users_id' => 15,
                'username' => 'USER',
            ),
            19 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-10 06:04:50',
                'customers_id' => 769,
                'id' => 138,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-10 06:04:50',
                'users_id' => 20,
                'username' => 'USER',
            ),
            20 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.33.16/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2021-03-29 09:48:08',
                'customers_id' => 740,
                'id' => 94,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2021-03-29 09:48:08',
                'users_id' => 15,
                'username' => 'USER',
            ),
            21 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.33.92/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2021-04-16 14:10:15',
                'customers_id' => 746,
                'id' => 108,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2021-04-16 14:10:15',
                'users_id' => 15,
                'username' => 'USER',
            ),
            22 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-10 06:04:50',
                'customers_id' => 771,
                'id' => 140,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-10 06:04:50',
                'users_id' => 20,
                'username' => 'USER',
            ),
            23 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-10 06:04:50',
                'customers_id' => 770,
                'id' => 139,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-10 06:04:50',
                'users_id' => 20,
                'username' => 'USER',
            ),
            24 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-18 10:12:33',
                'customers_id' => 769,
                'id' => 154,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-18 10:12:33',
                'users_id' => 14,
                'username' => 'USER',
            ),
            25 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.11/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2022-10-12 14:10:19',
                'customers_id' => 833,
                'id' => 130,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2022-10-12 14:10:19',
                'users_id' => 17,
                'username' => 'USER',
            ),
            26 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-16 08:44:11',
                'customers_id' => 769,
                'id' => 150,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-16 08:44:11',
                'users_id' => 18,
                'username' => 'USER',
            ),
            27 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2022-10-12 08:21:24',
                'customers_id' => 769,
                'id' => 125,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2022-10-12 08:21:24',
                'users_id' => 12,
                'username' => 'USER',
            ),
            28 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-02-18 06:44:31',
                'customers_id' => 770,
                'id' => 153,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-02-18 06:44:31',
                'users_id' => 23,
                'username' => 'USER',
            ),
            29 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.15/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-14 08:12:46',
                'customers_id' => 839,
                'id' => 160,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-14 08:12:46',
                'users_id' => 25,
                'username' => 'USER',
            ),
            30 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.11/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-14 08:12:47',
                'customers_id' => 833,
                'id' => 161,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-14 08:12:47',
                'users_id' => 25,
                'username' => 'USER',
            ),
            31 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:54:44',
                'customers_id' => 769,
                'id' => 162,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:54:44',
                'users_id' => 26,
                'username' => 'USER',
            ),
            32 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:54:44',
                'customers_id' => 770,
                'id' => 163,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:54:44',
                'users_id' => 26,
                'username' => 'USER',
            ),
            33 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:56:08',
                'customers_id' => 770,
                'id' => 164,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:56:08',
                'users_id' => 27,
                'username' => 'USER',
            ),
            34 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:56:08',
                'customers_id' => 769,
                'id' => 165,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:56:08',
                'users_id' => 27,
                'username' => 'USER',
            ),
            35 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:57:05',
                'customers_id' => 769,
                'id' => 166,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:57:05',
                'users_id' => 28,
                'username' => 'USER',
            ),
            36 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 09:57:05',
                'customers_id' => 770,
                'id' => 167,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 09:57:05',
                'users_id' => 28,
                'username' => 'USER',
            ),
            37 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 10:07:01',
                'customers_id' => 769,
                'id' => 168,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 10:07:01',
                'users_id' => 29,
                'username' => 'USER',
            ),
            38 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-03-16 10:07:01',
                'customers_id' => 770,
                'id' => 169,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-03-16 10:07:01',
                'users_id' => 29,
                'username' => 'USER',
            ),
            39 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.51.14/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-04-11 12:46:37',
                'customers_id' => 838,
                'id' => 170,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-04-11 12:46:37',
                'users_id' => 17,
                'username' => 'USER',
            ),
            40 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.54.8/pws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-04-12 09:17:15',
                'customers_id' => 427,
                'id' => 171,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-04-12 09:17:15',
                'users_id' => 30,
                'username' => 'USER',
            ),
            41 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/tfpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-05-02 09:39:57',
                'customers_id' => 769,
                'id' => 172,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-05-02 09:39:57',
                'users_id' => 31,
                'username' => 'USER',
            ),
            42 => 
            array (
                'active' => 'Y',
                'apiurl' => 'http://192.168.7.60/ttpws/pgapp',
                'client_id' => 'PGAPP',
                'client_secret' => 'H2WeWtqBFjWRCAFyvD30',
                'created_at' => '2023-05-02 09:39:57',
                'customers_id' => 770,
                'id' => 173,
                'last_token' => '',
                'password' => '2WtAJxo2fP9sLX81j4GE',
                'token_dt' => NULL,
                'updated_at' => '2023-05-02 09:39:57',
                'users_id' => 31,
                'username' => 'USER',
            ),
        ));
        Schema::enableForeignKeyConstraints();
        
    }
}