<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class CustomerGroupsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
		Schema::disableForeignKeyConstraints();	
        \DB::table('customer_groups')->delete();
        
        \DB::table('customer_groups')->insert(array (
            0 => 
            array (
                'id' => 2,
                'groupcode' => 'SLG001-1',
                'description' => 'DATO THOMAS GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => 'LIUNG YOONG SDN BHD',
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:29:16',
                'updated_at' => '2021-12-11 11:31:12',
            ),
            1 => 
            array (
                'id' => 3,
                'groupcode' => 'SLG002',
                'description' => 'DATO YEW CONSOLIDATE HQ GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '1800055704',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '18484',
                'agents_id' => NULL,
                'cfgfile' => '/cfg/consolidate/SLG002/PWS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:40:23',
                'updated_at' => '2021-03-22 09:20:52',
            ),
            2 => 
            array (
                'id' => 4,
                'groupcode' => 'SLG003',
                'description' => 'IPAJAK CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '1800055804',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '18322',
                'agents_id' => NULL,
                'cfgfile' => '/cfg/consolidate/SLG003/PWS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:42:19',
                'updated_at' => '2021-03-24 10:32:53',
            ),
            3 => 
            array (
                'id' => 5,
                'groupcode' => 'SLG004',
                'description' => 'BAN LEE CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '1800055759',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '16389',
                'agents_id' => 1,
                'cfgfile' => '/cfg/consolidate/SLG004/PWS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:44:09',
                'updated_at' => '2020-05-08 12:34:21',
            ),
            4 => 
            array (
                'id' => 6,
                'groupcode' => 'SLG005',
                'description' => 'SAYANG CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:44:57',
                'updated_at' => '2020-06-12 14:00:41',
            ),
            5 => 
            array (
                'id' => 7,
                'groupcode' => 'SLG006',
                'description' => 'MR LAM - PAHANG GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 08:45:46',
                'updated_at' => '2020-06-12 14:00:49',
            ),
            6 => 
            array (
                'id' => 10,
                'groupcode' => 'SLG007',
                'description' => 'PAPAJACK KENNY GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => 'PPJACK SDN BHD - PUCHONG',
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-04-05 16:39:45',
                'updated_at' => '2021-12-11 11:38:55',
            ),
            7 => 
            array (
                'id' => 11,
                'groupcode' => 'SLG008',
                'description' => 'MR YONG KTN GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:41:06',
                'updated_at' => '2020-06-12 14:00:58',
            ),
            8 => 
            array (
                'id' => 12,
                'groupcode' => 'SLG009',
                'description' => 'MR CHONG JOHOR GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:42:31',
                'updated_at' => '2020-06-12 14:01:07',
            ),
            9 => 
            array (
                'id' => 13,
                'groupcode' => 'SLG010',
                'description' => 'MR YAW JOHOR GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:43:06',
                'updated_at' => '2020-06-12 14:01:15',
            ),
            10 => 
            array (
                'id' => 14,
                'groupcode' => 'SLG011',
                'description' => 'MR HO - LIAN GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:44:07',
                'updated_at' => '2020-06-12 14:01:24',
            ),
            11 => 
            array (
                'id' => 15,
                'groupcode' => 'SLG012',
                'description' => 'DATO CHIN GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:45:21',
                'updated_at' => '2020-06-12 14:01:34',
            ),
            12 => 
            array (
                'id' => 16,
                'groupcode' => 'SLG013',
                'description' => 'KEPONG MR CHIN GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:50:15',
                'updated_at' => '2020-06-12 14:01:43',
            ),
            13 => 
            array (
                'id' => 17,
                'groupcode' => 'SLG014',
                'description' => 'MR TAN KEDAH GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:52:29',
                'updated_at' => '2020-06-12 13:56:37',
            ),
            14 => 
            array (
                'id' => 18,
                'groupcode' => 'SLG015',
                'description' => 'MR HO PERAK GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:55:01',
                'updated_at' => '2020-06-12 14:01:56',
            ),
            15 => 
            array (
                'id' => 19,
                'groupcode' => 'SLG016',
                'description' => 'MR FOO PERAK GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 07:55:53',
                'updated_at' => '2020-06-12 14:06:49',
            ),
            16 => 
            array (
                'id' => 20,
                'groupcode' => 'SLG017',
                'description' => 'MR TAN - MELAWATI GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:01:32',
                'updated_at' => '2020-06-12 14:08:03',
            ),
            17 => 
            array (
                'id' => 21,
                'groupcode' => 'SLG018',
                'description' => 'MR CHIN - SABAK GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:04:59',
                'updated_at' => '2020-06-12 14:08:10',
            ),
            18 => 
            array (
                'id' => 22,
                'groupcode' => 'SLG019',
                'description' => 'WILSON PUCHONG GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:05:57',
                'updated_at' => '2020-06-12 14:08:17',
            ),
            19 => 
            array (
                'id' => 23,
                'groupcode' => 'SLG020',
                'description' => 'JOHN - MERDEKA GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:09:00',
                'updated_at' => '2021-03-24 10:34:54',
            ),
            20 => 
            array (
                'id' => 24,
                'groupcode' => 'SLG021',
                'description' => 'DESMOND GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:12:12',
                'updated_at' => '2020-06-12 14:08:40',
            ),
            21 => 
            array (
                'id' => 25,
                'groupcode' => 'SLG022',
                'description' => 'DATO LIM GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:15:09',
                'updated_at' => '2020-06-12 14:08:51',
            ),
            22 => 
            array (
                'id' => 26,
                'groupcode' => 'SLG023',
                'description' => 'KUDAT MR WONG  GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:17:00',
                'updated_at' => '2020-06-12 14:09:02',
            ),
            23 => 
            array (
                'id' => 27,
                'groupcode' => 'SLG024',
                'description' => 'GARISAN CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '1800055788',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '16275',
                'agents_id' => 1,
                'cfgfile' => '/cfg/consolidate/SLG024/PWS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:20:21',
                'updated_at' => '2020-05-08 12:54:55',
            ),
            24 => 
            array (
                'id' => 28,
                'groupcode' => 'SLG025',
                'description' => 'FAJAMAS CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '1800055806',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '17063',
                'agents_id' => NULL,
                'cfgfile' => '/cfg/consolidate/SLG025/PWS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:25:40',
                'updated_at' => '2021-03-24 10:41:32',
            ),
            25 => 
            array (
                'id' => 29,
                'groupcode' => 'SLG026',
                'description' => 'REVENUE CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:27:09',
                'updated_at' => '2020-06-12 14:09:13',
            ),
            26 => 
            array (
                'id' => 30,
                'groupcode' => 'SLG027',
                'description' => 'LANGKAP CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:30:35',
                'updated_at' => '2020-06-12 14:09:25',
            ),
            27 => 
            array (
                'id' => 31,
                'groupcode' => 'SLG028',
                'description' => 'SELAYANG CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:31:35',
                'updated_at' => '2020-06-12 14:09:34',
            ),
            28 => 
            array (
                'id' => 32,
                'groupcode' => 'SLG029',
                'description' => 'VICKY CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:34:21',
                'updated_at' => '2020-06-12 14:09:43',
            ),
            29 => 
            array (
                'id' => 33,
                'groupcode' => 'SLG030',
                'description' => 'SABAH EHSAN CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:36:09',
                'updated_at' => '2020-06-12 14:09:51',
            ),
            30 => 
            array (
                'id' => 34,
                'groupcode' => 'SLG031',
                'description' => 'SWK HQ LS EMAS GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:37:42',
                'updated_at' => '2020-06-12 14:06:57',
            ),
            31 => 
            array (
                'id' => 35,
                'groupcode' => 'SLG032',
                'description' => 'SOO CONSOLIDATE GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:38:51',
                'updated_at' => '2020-06-12 14:07:17',
            ),
            32 => 
            array (
                'id' => 36,
                'groupcode' => 'SLG033-1',
                'description' => 'BEN - CONSOLIDATE SABAH GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:40:18',
                'updated_at' => '2021-03-24 10:50:24',
            ),
            33 => 
            array (
                'id' => 37,
                'groupcode' => 'SLG034-1',
                'description' => 'ANDREW GROUP',
                'customer_categories_id' => 1,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-05-06 08:42:54',
                'updated_at' => '2021-03-24 10:29:54',
            ),
            34 => 
            array (
                'id' => 38,
                'groupcode' => 'SLG035',
                'description' => 'K - HQ',
                'customer_categories_id' => 5,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '2200055531',
                'exp_dat' => '31/12/2100',
                'cfgpassword' => '24582',
                'agents_id' => NULL,
                'cfgfile' => '/cfg/consolidate/SLG035/MLS.CFG',
                'soft_lic' => 1,
                'created_at' => '2020-05-08 07:15:44',
                'updated_at' => '2020-10-30 13:00:49',
            ),
            35 => 
            array (
                'id' => 39,
                'groupcode' => 'SLG036',
                'description' => 'DANNY LIM GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => 'KPG SEHATI',
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-11-24 12:54:58',
                'updated_at' => '2021-12-13 13:07:00',
            ),
            36 => 
            array (
                'id' => 40,
                'groupcode' => 'SLG037',
                'description' => 'ION GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-11-29 08:01:45',
                'updated_at' => '2020-11-29 08:01:45',
            ),
            37 => 
            array (
                'id' => 41,
                'groupcode' => 'SLG038',
                'description' => 'MR LAM - JOHOR GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-12-21 07:16:34',
                'updated_at' => '2020-12-21 07:16:34',
            ),
            38 => 
            array (
                'id' => 42,
                'groupcode' => 'SLG039',
                'description' => 'WILLIAM GROUP',
                'customer_categories_id' => 1,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-12-21 07:17:14',
                'updated_at' => '2020-12-21 07:17:14',
            ),
            39 => 
            array (
                'id' => 43,
                'groupcode' => 'SLG040',
            'description' => 'AH LUN (KIAN LEE & YONG LI SENG)',
                'customer_categories_id' => 2,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-12-22 07:53:49',
                'updated_at' => '2020-12-22 08:04:44',
            ),
            40 => 
            array (
                'id' => 44,
                'groupcode' => 'SLG041',
            'description' => 'AH LUN(ANSENG CREDIT & COMPACT)',
                'customer_categories_id' => 5,
                'companyid' => 1,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2020-12-22 08:06:44',
                'updated_at' => '2020-12-22 08:07:31',
            ),
            41 => 
            array (
                'id' => 45,
                'groupcode' => 'SLG001-2',
                'description' => 'DATO THOMAS GROUP',
                'customer_categories_id' => 9,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2021-03-22 12:28:54',
                'updated_at' => '2021-03-23 10:04:32',
            ),
            42 => 
            array (
                'id' => 47,
                'groupcode' => 'SLG033-2',
                'description' => 'BEN - CONSOLIDATE SABAH GROUP',
                'customer_categories_id' => 2,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2021-03-24 10:46:55',
                'updated_at' => '2021-03-24 10:46:55',
            ),
            43 => 
            array (
                'id' => 46,
                'groupcode' => 'SLG034-2',
                'description' => 'ANDREW GROUP',
                'customer_categories_id' => 9,
                'companyid' => 2,
                'foldername' => NULL,
                'serial_no' => '',
                'exp_dat' => '',
                'cfgpassword' => '',
                'agents_id' => NULL,
                'cfgfile' => '',
                'soft_lic' => 1,
                'created_at' => '2021-03-24 10:30:25',
                'updated_at' => '2021-03-24 10:30:25',
            ),
        ));
        
		Schema::enableForeignKeyConstraints();	
    }
}