<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class LeaveformTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
		Schema::disableForeignKeyConstraints();
        \DB::table('leave_forms')->delete();
        
        \DB::table('leave_forms')->insert(array (
            0 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '12/01/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '16/01/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000001',
                'id' => 1,
                'leave_dat_frm' => '16/01/2023',
                'leave_dat_to' => '16/01/2023',
                'leave_duration' => '1.00',
            'leave_reason' => 'medical checkout (see doctor)',
                'leave_typ' => 'Annual',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            1 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '20/01/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '20/01/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000002',
                'id' => 2,
                'leave_dat_frm' => '25/01/2023',
                'leave_dat_to' => '26/01/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'CHINESE NEW YEAR HOLIDAY',
                'leave_typ' => 'Annual',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            2 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '20/01/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '20/01/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000003',
                'id' => 3,
                'leave_dat_frm' => '25/01/2023',
                'leave_dat_to' => '25/01/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'back to kampung',
                'leave_typ' => 'Annual',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            3 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '06/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '06/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000004',
                'id' => 4,
                'leave_dat_frm' => '13/02/2023',
                'leave_dat_to' => '13/02/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'got personal things to do',
                'leave_typ' => 'Annual',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            4 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '17/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '17/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000005',
                'id' => 5,
                'leave_dat_frm' => '30/01/2023',
                'leave_dat_to' => '31/01/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'COVID-19 Quarantine',
                'leave_typ' => 'M.C',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            5 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '17/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '17/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000006',
                'id' => 6,
                'leave_dat_frm' => '02/02/2023',
                'leave_dat_to' => '04/02/2023',
                'leave_duration' => '3.00',
                'leave_reason' => 'COVID-19 Quarantine',
                'leave_typ' => 'M.C',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            6 => 
            array (
                'applied_by' => 'STANLEY',
                'applied_dat' => '27/01/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '27/01/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE MANAGER',
                'doc_no' => 'LF00000007',
                'id' => 7,
                'leave_dat_frm' => '27/01/2023',
                'leave_dat_to' => '02/02/2023',
                'leave_duration' => '5.00',
                'leave_reason' => 'Covid Home Isolation Or Surveillance Order',
                'leave_typ' => 'M.C',
                'staff_name' => 'STANLEY LOH CHEE KUAN',
                'staffid' => 4,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            7 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '04/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '06/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000008',
                'id' => 8,
                'leave_dat_frm' => '04/02/2023',
                'leave_dat_to' => '04/02/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'covid',
                'leave_typ' => 'M.C',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            8 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '06/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '06/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000009',
                'id' => 9,
                'leave_dat_frm' => '06/02/2023',
                'leave_dat_to' => '06/02/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'covid',
                'leave_typ' => 'M.C',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            9 => 
            array (
                'applied_by' => 'KIEW',
                'applied_dat' => '20/02/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '28/02/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SUPPORT ENGINEER',
                'doc_no' => 'LF00000010',
                'id' => 10,
                'leave_dat_frm' => '17/03/2023',
                'leave_dat_to' => '17/03/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'daughter first day in standard 1',
                'leave_typ' => 'Annual',
                'staff_name' => 'TSEN FUN KIEW',
                'staffid' => 3,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            10 => 
            array (
                'applied_by' => 'STANLEY',
                'applied_dat' => '27/02/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '17/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE MANAGER',
                'doc_no' => 'LF00000011',
                'id' => 11,
                'leave_dat_frm' => '17/03/2023',
                'leave_dat_to' => '17/03/2023',
                'leave_duration' => '0.50',
                'leave_reason' => 'Son school orientation day',
                'leave_typ' => 'Annual',
                'staff_name' => 'STANLEY LOH CHEE KUAN',
                'staffid' => 4,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            11 => 
            array (
                'applied_by' => 'KIEW',
                'applied_dat' => '28/02/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '03/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SUPPORT ENGINEER',
                'doc_no' => 'LF00000012',
                'id' => 12,
                'leave_dat_frm' => '21/02/2023',
                'leave_dat_to' => '21/02/2023',
                'leave_duration' => '0.50',
                'leave_reason' => 'mc',
                'leave_typ' => 'M.C',
                'staff_name' => 'TSEN FUN KIEW',
                'staffid' => 3,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            12 => 
            array (
                'applied_by' => 'KIEW',
                'applied_dat' => '28/02/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '08/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SUPPORT ENGINEER',
                'doc_no' => 'LF00000013',
                'id' => 13,
                'leave_dat_frm' => '27/02/2023',
                'leave_dat_to' => '27/02/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'mc',
                'leave_typ' => 'M.C',
                'staff_name' => 'TSEN FUN KIEW',
                'staffid' => 3,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            13 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '09/03/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '13/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000014',
                'id' => 14,
                'leave_dat_frm' => '08/04/2023',
                'leave_dat_to' => '08/04/2023',
                'leave_duration' => '0.50',
                'leave_reason' => 'tomb sweeping',
                'leave_typ' => 'Annual',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            14 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '09/03/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '13/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000015',
                'id' => 15,
                'leave_dat_frm' => '10/04/2023',
                'leave_dat_to' => '13/04/2023',
                'leave_duration' => '4.00',
                'leave_reason' => 'travel',
                'leave_typ' => 'Annual',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            15 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '16/03/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '18/03/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000016',
                'id' => 16,
                'leave_dat_frm' => '18/03/2023',
                'leave_dat_to' => '18/03/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'Tomb-sweeping with family',
                'leave_typ' => 'Annual',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            16 => 
            array (
                'applied_by' => 'LIM',
                'applied_dat' => '11/04/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '13/04/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000017',
                'id' => 17,
                'leave_dat_frm' => '17/04/2023',
                'leave_dat_to' => '17/04/2023',
                'leave_duration' => '0.50',
            'leave_reason' => 'medical checkup (meet doctor)',
                'leave_typ' => 'Annual',
                'staff_name' => 'LIM QING WEI',
                'staffid' => 6,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            17 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '16/04/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '18/04/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000018',
                'id' => 18,
                'leave_dat_frm' => '20/04/2023',
                'leave_dat_to' => '21/04/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'Personal Leave',
                'leave_typ' => 'Annual',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            18 => 
            array (
                'applied_by' => 'KIEW',
                'applied_dat' => '17/04/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '29/04/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SUPPORT ENGINEER',
                'doc_no' => 'LF00000019',
                'id' => 19,
                'leave_dat_frm' => '29/05/2023',
                'leave_dat_to' => '30/05/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'go out with family',
                'leave_typ' => 'Annual',
                'staff_name' => 'TSEN FUN KIEW',
                'staffid' => 3,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            19 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '18/04/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '29/04/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000020',
                'id' => 20,
                'leave_dat_frm' => '17/04/2023',
                'leave_dat_to' => '17/04/2023',
                'leave_duration' => '0.20',
                'leave_reason' => 'Personal matters',
                'leave_typ' => 'Emergency',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            20 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '17/05/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '18/05/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000021',
                'id' => 21,
                'leave_dat_frm' => '18/05/2023',
                'leave_dat_to' => '18/05/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'Family matters',
                'leave_typ' => 'Annual',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            21 => 
            array (
                'applied_by' => 'CHEW',
                'applied_dat' => '17/05/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '18/05/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000022',
                'id' => 22,
                'leave_dat_frm' => '26/05/2023',
                'leave_dat_to' => '26/05/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'Family matters',
                'leave_typ' => 'Annual',
                'staff_name' => 'CALDREN CHEW KAI XIN',
                'staffid' => 8,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            22 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '30/05/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '30/05/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000023',
                'id' => 23,
                'leave_dat_frm' => '23/05/2023',
                'leave_dat_to' => '25/05/2023',
                'leave_duration' => '3.00',
                'leave_reason' => 'covid positive',
                'leave_typ' => 'M.C',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            23 => 
            array (
                'applied_by' => 'BRYAN',
                'applied_dat' => '30/05/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '30/05/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER',
                'doc_no' => 'LF00000024',
                'id' => 24,
                'leave_dat_frm' => '02/06/2023',
                'leave_dat_to' => '03/06/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'body check',
                'leave_typ' => 'Annual',
                'staff_name' => 'LAU ZHEN FEI',
                'staffid' => 7,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            24 => 
            array (
                'applied_by' => 'JASON',
                'applied_dat' => '30/05/2023',
                'approved_by' => 'TSEN',
                'approved_dat' => '31/05/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE PROGRAMMER/ SUPPORT',
                'doc_no' => 'LF00000025',
                'id' => 25,
                'leave_dat_frm' => '25/05/2023',
                'leave_dat_to' => '27/05/2023',
                'leave_duration' => '3.00',
                'leave_reason' => 'Covid positive',
                'leave_typ' => 'M.C',
                'staff_name' => 'JASON CHAI JA SON',
                'staffid' => 9,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            25 => 
            array (
                'applied_by' => 'KIEW',
                'applied_dat' => '12/06/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '16/06/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SUPPORT ENGINEER',
                'doc_no' => 'LF00000026',
                'id' => 26,
                'leave_dat_frm' => '17/06/2023',
                'leave_dat_to' => '17/06/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'wife medical checkup, i need to fetch her to hospital and take care of my childs.',
                'leave_typ' => 'Annual',
                'staff_name' => 'TSEN FUN KIEW',
                'staffid' => 3,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            26 => 
            array (
                'applied_by' => 'JASON',
                'applied_dat' => '13/06/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '16/06/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000027',
                'id' => 27,
                'leave_dat_frm' => '12/06/2023',
                'leave_dat_to' => '12/06/2023',
                'leave_duration' => '1.00',
                'leave_reason' => 'sick',
                'leave_typ' => 'M.C',
                'staff_name' => 'JASON CHAI JA SON',
                'staffid' => 9,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
            27 => 
            array (
                'applied_by' => 'JASON',
                'applied_dat' => '15/06/2023',
                'approved_by' => 'PYCHAN',
                'approved_dat' => '16/06/2023',
                'created_at' => '2023-07-11 10:01:09',
                'designation' => 'SOFTWARE SUPPORT/PRO',
                'doc_no' => 'LF00000028',
                'id' => 28,
                'leave_dat_frm' => '13/06/2023',
                'leave_dat_to' => '14/06/2023',
                'leave_duration' => '2.00',
                'leave_reason' => 'influenza positive',
                'leave_typ' => 'M.C',
                'staff_name' => 'JASON CHAI JA SON',
                'staffid' => 9,
                'status' => 1,
                'updated_at' => '2023-07-11 10:01:09',
            ),
        ));
        
        Schema::enableForeignKeyConstraints();
    }
}