<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrainingformdetailTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('training_form_details')->delete();

        \DB::table('training_form_details')->insert(array (
            0 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 12,
                'input_flag' => 0,
                'no' => '8',
                'particular' => 'Explain What Is High Risk Country',
                'seq' => 10,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:32:25',
            ),
            1 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 13,
                'input_flag' => 0,
                'no' => '9',
                'particular' => 'Explain What Is Search List',
                'seq' => 11,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:32:25',
            ),
            2 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 14,
                'input_flag' => 0,
                'no' => '10',
                'particular' => 'Explain The Conditions Of Check For The Amount Pawn / Repawn / Redeem',
                'seq' => 13,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:37:04',
            ),
            3 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 15,
                'input_flag' => 0,
                'no' => '11',
                'particular' => 'Explain What Is CDD & Enhance CDD',
                'seq' => 12,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:37:04',
            ),
            4 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 16,
                'input_flag' => 0,
                'no' => '12',
                'particular' => 'Explain When To Capture Passport Or IC No. By Using Camera If Any',
                'seq' => 14,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:32:25',
            ),
            5 =>
            array (
                'created_at' => '2021-08-24 10:32:25',
                'id' => 17,
                'input_flag' => 0,
                'no' => '13',
                'particular' => 'Redeem And Repawn Explanation',
                'seq' => 15,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 2,
                'updated_at' => '2021-08-24 10:32:25',
            ),
            6 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 26,
                'input_flag' => 0,
                'no' => '1',
                'particular' => 'Setup Company Details',
                'seq' => 1,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 08:55:26',
            ),
            7 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 27,
                'input_flag' => 0,
                'no' => '2',
                'particular' => 'Setup System Requirements',
                'seq' => 2,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            8 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 28,
                'input_flag' => 0,
                'no' => '3',
                'particular' => 'Setup Group and User Password rules',
                'seq' => 3,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            9 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 29,
                'input_flag' => 0,
                'no' => '4',
                'particular' => 'Gold Type Maintenance',
                'seq' => 4,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            10 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 30,
                'input_flag' => 0,
                'no' => '5',
                'particular' => 'Category Maintenance',
                'seq' => 5,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            11 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 31,
                'input_flag' => 0,
                'no' => '6',
                'particular' => 'Pattern Maintenance',
                'seq' => 6,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            12 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 32,
                'input_flag' => 0,
                'no' => '7',
                'particular' => 'Supplier Information / Customer Information',
                'seq' => 7,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            13 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 33,
                'input_flag' => 0,
                'no' => '8',
                'particular' => 'Salesperson Information or Agent Information',
                'seq' => 8,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-11-07 09:03:59',
            ),
            14 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 34,
                'input_flag' => 0,
                'no' => '9',
                'particular' => 'Credit Card Information include Bank Information',
                'seq' => 9,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-11-07 09:03:59',
            ),
            15 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 35,
                'input_flag' => 0,
                'no' => '10',
            'particular' => 'Branch Information (for those more than 1 branch)',
                'seq' => 10,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            16 =>
            array (
                'created_at' => '2021-08-24 10:43:16',
                'id' => 36,
                'input_flag' => 0,
                'no' => '11',
                'particular' => 'Daily Work :-',
                'seq' => 11,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:16',
            ),
            17 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 37,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Gold Price',
                'seq' => 12,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            18 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 38,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Purchase of Stock (need sticker or stock number only) with / without photo taken',
                'seq' => 13,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-11-07 09:05:20',
            ),
            19 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 39,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Edit Purchase of Stock',
                'seq' => 14,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            20 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 40,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Purchase Return to Supplier (can be return direct or write-off only)',
                'seq' => 15,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            21 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 41,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Purchase of Accesserios (no stock number)',
                'seq' => 16,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            22 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 42,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Purchase of Accesserios',
                'seq' => 17,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            23 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 43,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Trade-in Stock only',
                'seq' => 18,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            24 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 44,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>New Sales',
                'seq' => 19,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            25 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 45,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Edit Sales',
                'seq' => 20,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            26 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 46,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>New Job Order',
                'seq' => 21,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            27 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 47,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Edit Job Order',
                'seq' => 22,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            28 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 48,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Payment of Job Order',
                'seq' => 23,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            29 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 49,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Sales Return from Customer (need sticker to print if any)',
                'seq' => 24,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            30 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 50,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Extra Services (ie:rental or cleaning of gold)',
                'seq' => 25,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            31 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 51,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Expenses (cash payment only)',
                'seq' => 26,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            32 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 52,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Sold Gold to Supplier',
                'seq' => 27,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            33 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 53,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Excess Return (return by weight only - for exchange purpose)',
                'seq' => 28,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            34 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 54,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Check Stock Item Details',
                'seq' => 29,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            35 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 55,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Bin Location Transfer',
                'seq' => 30,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            36 =>
            array (
                'created_at' => '2021-08-24 10:43:17',
                'id' => 56,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Transfer Out/Receive In (for transfer inter-branch purpose)',
                'seq' => 31,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:43:17',
            ),
            37 =>
            array (
                'created_at' => '2021-08-24 10:44:40',
                'id' => 57,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Daily Reports ie:-',
                'seq' => 32,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:44:40',
            ),
            38 =>
            array (
                'created_at' => '2021-08-24 10:44:40',
                'id' => 58,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Purchase from Supplier',
                'seq' => 33,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:10',
            ),
            39 =>
            array (
                'created_at' => '2021-08-24 10:48:23',
                'id' => 59,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Sales Profit Analysis',
                'seq' => 34,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:10',
            ),
            40 =>
            array (
                'created_at' => '2021-08-24 10:48:23',
                'id' => 60,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Sales by Credit card',
                'seq' => 35,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:10',
            ),
            41 =>
            array (
                'created_at' => '2021-08-24 10:48:23',
                'id' => 61,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Job Order Analysis',
                'seq' => 36,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:10',
            ),
            42 =>
            array (
                'created_at' => '2021-08-24 10:48:23',
                'id' => 62,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Combine Analysis',
                'seq' => 37,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:11',
            ),
            43 =>
            array (
                'created_at' => '2021-08-24 10:48:24',
                'id' => 63,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Stock Movement',
                'seq' => 38,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:11',
            ),
            44 =>
            array (
                'created_at' => '2021-08-24 10:48:24',
                'id' => 64,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '- Stock Sticker (if any)',
                'seq' => 39,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:11',
            ),
            45 =>
            array (
                'created_at' => '2021-08-24 10:48:24',
                'id' => 65,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Other reports',
                'seq' => 40,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-28 09:09:11',
            ),
            46 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 66,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Backup Data',
                'seq' => 41,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            47 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 67,
                'input_flag' => 0,
                'no' => '12',
            'particular' => 'Monthly Work:- (after daily printing and backup process)',
                'seq' => 42,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            48 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 68,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Sales Profit Analysis by Gold Category',
                'seq' => 43,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            49 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 69,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Monthly Account Summary',
                'seq' => 44,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            50 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 70,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>MTD/YTD Summary Report',
                'seq' => 45,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            51 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 71,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Stock Balance Details - Stock Balance By Bin No',
                'seq' => 46,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            52 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 72,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Close Month-End process',
                'seq' => 47,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            53 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 73,
                'input_flag' => 0,
                'no' => '13',
            'particular' => 'Year End Process :- (if need for re-entry and check stock balance)',
                'seq' => 48,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            54 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 74,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Stock Take (Year End)',
                'seq' => 49,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            55 =>
            array (
                'created_at' => '2021-08-24 10:52:29',
                'id' => 75,
                'input_flag' => 0,
                'no' => '14',
                'particular' => 'Others Amendment :-',
                'seq' => 50,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:29',
            ),
            56 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 76,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Sold Date Correction',
                'seq' => 51,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            57 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 77,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Purchase Date Correction',
                'seq' => 52,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            58 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 78,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Purchase Return Date Correction',
                'seq' => 53,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            59 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 79,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Customer Return Date Correction',
                'seq' => 54,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            60 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 80,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Delete Item Range',
                'seq' => 55,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            61 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 81,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Lampiran 2 (Custom GST only if any)',
                'seq' => 56,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            62 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 82,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Others',
                'seq' => 57,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            63 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 83,
                'input_flag' => 0,
                'no' => '15',
                'particular' => 'Management Reports :-',
                'seq' => 58,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            64 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 84,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Top Sales Analysis',
                'seq' => 59,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            65 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 85,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Monthly Sales Analysis',
                'seq' => 60,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            66 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 86,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Real Stock Balance Check (if manage for stock level)',
                'seq' => 61,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            67 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 87,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Consolidate Reports (for those more than 1 branch)',
                'seq' => 62,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            68 =>
            array (
                'created_at' => '2021-08-24 10:52:30',
                'id' => 88,
                'input_flag' => 0,
                'no' => '16',
                'particular' => 'Disaster for Data Restore if any',
                'seq' => 63,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 3,
                'updated_at' => '2021-08-24 10:52:30',
            ),
            69 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 89,
                'input_flag' => 0,
                'no' => '1',
                'particular' => 'Explain login screen function',
                'seq' => 1,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            70 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 90,
                'input_flag' => 0,
                'no' => '2',
                'particular' => 'Setup Company Details',
                'seq' => 2,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            71 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 91,
                'input_flag' => 0,
                'no' => '3',
                'particular' => 'Setup Group and User Password rules',
                'seq' => 3,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            72 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 92,
                'input_flag' => 0,
                'no' => '4',
                'particular' => 'Maintenance function Explanation – customer, stock category, gold type, condition',
                'seq' => 4,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            73 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 93,
                'input_flag' => 0,
                'no' => '5',
                'particular' => 'Maintenance function Explanation – race,insurance policy and nationality',
                'seq' => 5,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            74 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 94,
                'input_flag' => 0,
                'no' => '6',
                'particular' => 'Daily Work :-',
                'seq' => 6,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            75 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 95,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Pawn screen explanation',
                'seq' => 7,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            76 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 96,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Redeem and Repawn explanation',
                'seq' => 8,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            77 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 97,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Edit ticket explanation',
                'seq' => 9,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            78 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 98,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Group redeem &repawn explanation or Group Pawn,Redeem & Repawn explaination',
                'seq' => 10,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-11-07 09:02:04',
            ),
            79 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 99,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Redeem/repawn 2nd slip explanation',
                'seq' => 11,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            80 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 100,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Check Ticket by IC & pawn no explanation',
                'seq' => 12,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            81 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 101,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Daily Reports ie:-',
                'seq' => 13,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            82 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 102,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '- Daily Pawn (Peraturan 11)',
                'seq' => 14,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            83 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 103,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Redeem',
                'seq' => 15,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            84 =>
            array (
                'created_at' => '2021-08-28 11:29:39',
                'id' => 104,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '- Daily Extend (if any)',
                'seq' => 16,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:39',
            ),
            85 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 105,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Daily Summary',
                'seq' => 17,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            86 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 106,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '- Other Reports',
                'seq' => 18,
                'space_lvl' => 1,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            87 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 107,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Data Backup',
                'seq' => 19,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            88 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 108,
                'input_flag' => 0,
                'no' => '7',
            'particular' => 'Monthly Work:- (after daily printing and backup process)',
                'seq' => 20,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            89 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 109,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Month End Close explanation (same for year end process)',
                'seq' => 21,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            90 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 110,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Stock Analysis (UTD)',
                'seq' => 22,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            91 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 111,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Monthly Summary Report',
                'seq' => 23,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            92 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 112,
                'input_flag' => 0,
                'no' => '8',
                'particular' => 'Expire Stock Process :-',
                'seq' => 24,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            93 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 113,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>unredeem report explanation',
                'seq' => 25,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            94 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 114,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Issue reminder explanation',
                'seq' => 26,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            95 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 115,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Pre auction List explanation',
                'seq' => 27,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            96 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 116,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Auction (Jadual N) explanation',
                'seq' => 28,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            97 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 117,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Jadual M (peraturan 13) explanation',
                'seq' => 29,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            98 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 118,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Jadual O explanation',
                'seq' => 30,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            99 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 119,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Write Off explanation',
                'seq' => 31,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            100 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 120,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Group sold & sold items explanation',
                'seq' => 32,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            101 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 121,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Reports ie: Write-Off,Daily Sold',
                'seq' => 33,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            102 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 122,
                'input_flag' => 0,
                'no' => '9',
                'particular' => 'Others Amendment :-',
                'seq' => 34,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            103 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 123,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Reset functions include reset redeem, reset extend,reset reminder,',
                'seq' => 35,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            104 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 124,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Reset pre-auction,reset auction,reset group sold,reset write-off',
                'seq' => 36,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            105 =>
            array (
                'created_at' => '2021-08-28 11:29:40',
                'id' => 125,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Others',
                'seq' => 37,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:40',
            ),
            106 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 126,
                'input_flag' => 0,
                'no' => '10',
                'particular' => 'Year-End Process :-',
                'seq' => 38,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            107 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 127,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Lampiran A report explanation',
                'seq' => 39,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            108 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 128,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Check forecast redeem interest analysis (accrual tax) report explanation',
                'seq' => 40,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            109 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 129,
                'input_flag' => 0,
                'no' => '11',
                'particular' => 'Management Reports :-',
                'seq' => 41,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            110 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 130,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Top Sales Analysis',
                'seq' => 42,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            111 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 131,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Monthly Sales Analysis',
                'seq' => 43,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            112 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 132,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Real Stock Balance Check (if manage for stock level)',
                'seq' => 44,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            113 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 133,
                'input_flag' => 0,
                'no' => NULL,
            'particular' => '>Consolidate Reports (for those more than 1 branch)',
                'seq' => 45,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            114 =>
            array (
                'created_at' => '2021-08-28 11:29:41',
                'id' => 134,
                'input_flag' => 0,
                'no' => '12',
                'particular' => 'Disaster for Data Restore if any',
                'seq' => 46,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 4,
                'updated_at' => '2021-08-28 11:29:41',
            ),
            115 =>
            array (
                'created_at' => '2021-11-07 08:54:37',
                'id' => 135,
                'input_flag' => 0,
                'no' => '1',
                'particular' => 'Explain login screen function',
                'seq' => 1,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:54:37',
            ),
            116 =>
            array (
                'created_at' => '2021-11-07 08:54:58',
                'id' => 136,
                'input_flag' => 0,
                'no' => '2',
                'particular' => 'Setup Company Details',
                'seq' => 2,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:54:58',
            ),
            117 =>
            array (
                'created_at' => '2021-11-07 08:55:19',
                'id' => 137,
                'input_flag' => 0,
                'no' => '3',
                'particular' => 'Setup Group and User Password rules',
                'seq' => 3,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:55:19',
            ),
            118 =>
            array (
                'created_at' => '2021-11-07 08:57:39',
                'id' => 138,
                'input_flag' => 0,
                'no' => '4',
                'particular' => 'Maintenance function Explanation – customer, stock category, gold type, condition',
                'seq' => 4,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:57:39',
            ),
            119 =>
            array (
                'created_at' => '2021-11-07 08:58:02',
                'id' => 139,
                'input_flag' => 0,
                'no' => '5',
                'particular' => 'Maintenance function Explanation – race,insurance policy and nationality',
                'seq' => 5,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:58:02',
            ),
            120 =>
            array (
                'created_at' => '2021-11-07 08:58:18',
                'id' => 140,
                'input_flag' => 0,
                'no' => '6',
                'particular' => 'Daily Work :-',
                'seq' => 6,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:58:18',
            ),
            121 =>
            array (
                'created_at' => '2021-11-07 08:59:03',
                'id' => 141,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Loan Screen Explaination',
                'seq' => 7,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 08:59:03',
            ),
            122 =>
            array (
                'created_at' => '2021-11-07 09:00:12',
                'id' => 142,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Edit Loan Explaination',
                'seq' => 8,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 09:00:12',
            ),
            123 =>
            array (
                'created_at' => '2021-11-07 09:00:12',
                'id' => 143,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Payment Screen Explaination',
                'seq' => 9,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 09:00:12',
            ),
            124 =>
            array (
                'created_at' => '2021-11-07 09:01:21',
                'id' => 144,
                'input_flag' => 0,
                'no' => NULL,
                'particular' => '>Check Loan by IC & Doc no Explanation',
                'seq' => 10,
                'space_lvl' => 0,
                'special' => 0,
                'trainingid' => 7,
                'updated_at' => '2021-11-07 09:01:21',
            ),
        ));


    }
}
